### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by Runakko** [c4ln/Stealer#1]
**I get an error while compiling, please tell me how to run.**
`error[E0560]: struct `User` has no field named `hostname`
   --> src\main.rs:150:9
    |
150 |         hostname: whoami::hostname(),
    |         ^^^^^^^^ `User` does not have this field
    |
    = note: available fields are: `ip`, `username`, `password`

error[E0609]: no field `hostname` on type `User`
   --> src\main.rs:161:32
    |
161 |         result.push_str(&*user.hostname);
    |                                ^^^^^^^^ unknown field
    |
    = note: available fields are: `ip`, `username`, `password`

Some errors have detailed explanations: E0560, E0609.
For more information about an error, try `rustc --explain E0560`.
error: could not compile `stealer` due to 2 previous errors`

**Comment by c4ln** [comment]
will fix later

**Comment by c4ln** [comment]
fixed @Runakko

**Comment by VioletteCrew** [comment]
thx
